### ISSUE TITLE
add .py[co] build dist *.egg-info .hgignore to .gitignore

### ISSUE THREAD

**Issue by jfkw** [feuervogel/django-taggit-templatetags#1]
django-taggit-templatetags looks useful. One git note, the following directories and files and are present as of aad78b. It might be best to add these to .gitignore:

build
dist
django_taggit_templatetags.egg-info
.hgignore
./taggit_templatetags/**init**.pyc

**Comment by feuervogel** [comment]
thanks for that hint, done that. since i'm using mercurial (with hg-git), I've added the paths to .hgignore.
